[project]
name = "reywechat"
version = "1.1.45"
description = "WeChat client control framework based on a WeChat client Hook program."
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
keywords = [
    "rey",
    "reyxbo",
    "wechat",
    "robot",
    "receive",
    "send",
    "client"
]
authors = [
    {name = "Rey", email = "reyxbo@163.com"}
]
dependencies = [
    "reydb",
    "reykit",
    "reyserver"
]

[project.urls]
Homepage = "https://www.reyxbo.com/release/python/reywechat"
Repository = "https://github.com/reyxbo/reywechat-py.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
